### ISSUE TITLE
Add the option set generator in nvram

### ISSUE THREAD

**Issue by jonisc** [GeoSn0w/Yalu-Jailbreak-iOS-10.2#10]
It would be great to have a textfield where you set your generator (the field should not clear itself after reboot / reinstall of yaludark) so you can restore via Prometheus. 
http://reddit.com/r/jailbreak/comments/5zmk8h/tutorialdiscussion_how_to_put_your_generator_into/?ref=search_posts
Maybe write the generator to /var/mobile/.shsh2generator
I don't know if it's possible to read the file in this mode already. 
Please chmod it sothat only root:root can read + write it. Mobile should not be able to modify it.

**Comment by GeoSn0w** [comment]
I will consider that

**Comment by GeoSn0w** [comment]
Closed as not being an issue.
