### ISSUE TITLE
Issue opening XcodeProject

### ISSUE THREAD

**Issue by teh-random-name** [GeoSn0w/Yalu-Jailbreak-iOS-10.2#13]
Tried opening the `xcodeproj` and Xcode complains that it can't be opened.
Use Xcode 8.3.2 (8E2002) on Sierra 10.12.4

**Comment by GeoSn0w** [comment]
Apparently the file gets damaged when I upload it via browser, will add it later via client.

**Comment by GeoSn0w** [comment]
I've added the full project as a ZIP, feel free to download it.
