### ISSUE TITLE
Yalu Dark crashes on reboot, but the normal yalu102 doesn't.

### ISSUE THREAD

**Issue by FranticUmbreon** [GeoSn0w/Yalu-Jailbreak-iOS-10.2#6]
Just as the title says.

**Comment by GeoSn0w** [comment]
That's kinda hard to imagine considering that it is the same code.
What device, what iOS version, any list of tweaks? Maybe some sketchy Immortal or certtime?

**Comment by ridalarry** [comment]
@geoSn0w is Dark Yalu incompatible with Immortal?

**Comment by GeoSn0w** [comment]
Of course, most of the apps are

**Comment by GeoSn0w** [comment]
Closed as the user hasn't replayed in over 14 days.
