### ISSUE TITLE
Doesn't renew with extender

### ISSUE THREAD

**Issue by ridalarry** [GeoSn0w/Yalu-Jailbreak-iOS-10.2#8]
It doesn't renew using ext3nder tweak while normal yalu does

**Comment by GeoSn0w** [comment]
I never heard of that tweak.

**Comment by portalgamesmais** [comment]
It's not a tweak it's an app made by saurik

**Comment by portalgamesmais** [comment]
The tweak it's just a way to use it without devlepoer account

**Comment by GeoSn0w** [comment]
That is Extender not ext3nder. And Yalu Dark works fine with Cydia Exntender.

**Comment by portalgamesmais** [comment]
Yes I know ext3nder is a tweak that makes extender work without developer id

**Comment by portalgamesmais** [comment]
And yes Yalu dark works with ext3nder for me but it doesn't open when I'm in non jailbroken state

**Comment by GeoSn0w** [comment]
You have Immortal Installed?

**Comment by portalgamesmais** [comment]
No

**Comment by GeoSn0w** [comment]
I confirm having ext3nder getting installed correctly the Yalu Dark

**Comment by portalgamesmais** [comment]
It installs but I can open it after rebooting

**Comment by portalgamesmais** [comment]
Can't *

**Comment by GeoSn0w** [comment]
Trust the profile?

**Comment by GeoSn0w** [comment]
Closed as the user hasn't replied in over 12 days.
